version: '2'
services:
  test-runner:
    image: node
    container_name: te_front_end_tests
    env_file:
      - test-runner.env
    environment:
      - COVERALLS_REPO_TOKEN
    volumes:
      - "${PROJ_DIR}:${PROJ_DIR}"
      - ./scripts:/scripts
    command: bash -c "cd ${PROJ_DIR} 
                      && echo ${AUDIO_LIB}
                      && npm install
                      && rm ${AUDIO_LIB}
                      && cp ${AUDIO_SCRIPT} ${AUDIO_LIB}
                      && npm run test:ci --silent" 
    network_mode: "host"

#&& cat src/__test__/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
