version: '2'
services:
  test-runner:
    image: node
    container_name: te_front_end_tests
    environment:
      - COVERALLS_REPO_TOKEN
    volumes:
      - "${WORKSPACE}:/translationExchange"
      - ./scripts:/scripts
    command: bash -c "cd /translationExchange 
                      && npm install
                      && rm /translationExchange/node_modules/react-mic-plus/lib/libs/AudioContext.js
                      && cp /scripts/AudioContext.js /translationExchange/node_modules/react-mic-plus/lib/libs/AudioContext.js
                      && npm run test:ci --silent 
                      && cat src/__test__/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
    network_mode: "host"
