sudo: required

#language: node_js

services:
  - docker

before_install:
  - chmod +x set-up-travis.sh

install:
  - source set-up-travis.sh
  - cd src/__test__/test_container
  - docker-compose build backend_server

script:
  - docker-compose up -d
  - docker-compose -f test-runner.yml run --rm test-runner

after_script:
  - docker-compose down
  - docker ps -aq
