sudo: required
language: node_js
node_js:
  - "7"
env:
  global:
    - "PROJ_DIR=${TRAVIS_BUILD_DIR}"
services:
  - docker
git:
  depth: 1
before_install:
  - chmod +x extra-setup.sh
  - source extra-setup.sh
  - env
install:
  - cd src/__test__/test_container
  - docker-compose build backend_server
script:
  - docker-compose up -d
  - docker ps -a
  - docker-compose -f test-runner.yml run --rm test-runner
afer_script:
  - docker-compose down
cache:
  directories:
    - $HOME/.m2/repository
    - "${PROJ_DIR}/node_modules"
